spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: 123456


mybatis:
      type-aliases-package: com.zztian.demo.bean
